<a href="https://colab.research.google.com/github/washingtonjr8/PIBIC/blob/main/Numero_de_casos_e_%C3%B3bitos_(FM).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [ ]:
path = '/content/drive/MyDrive/Colab Notebooks/PIBIC/Dados FM/'
ano_inicio = 7
ano_fim = 21
input_files = ['FMACBR'+ str(ano)+'.csv' for ano in range(ano_inicio, ano_fim)]

df_list = []

for file in input_files:
    df_list.append(pd.read_csv(path+file, encoding='latin1', index_col=False, engine='python',on_bad_lines='skip', delimiter = ';'))

df = pd.concat(df_list, axis=0, ignore_index=True)
df




Unnamed: 0  TP_NOT ID_AGRAVO  DT_NOTIFIC  SEM_NOT  NU_ANO  SG_UF_NOT  \
0               1       2      A779  2007-01-03   200701    2007         35   
1               2       2      A779  2007-01-29   200705    2007         41   
2               3       2      A779  2007-01-10   200702    2007         31   
3               4       2      A779  2007-01-18   200703    2007         42   
4               5       2      A779  2007-01-15   200703    2007         42   
...           ...     ...       ...         ...      ...     ...        ...   
33784        1965       2      A779  2020-12-30   202053    2020         35   
33785        1966       2      A779  2020-12-31   202053    2020         35   
33786        1967       2      A779  2020-12-31   202053    2020         17   
33787        1968       2      A779  2020-12-31   202053    2020         35   
33788        1969       2      A779  2020-12-31   202053    2020         35   

       ID_MUNICIP  ID_REGIONA  ID_UNIDADE  ... DIAG_DESCA  TPAUTOCTO  COUFINF  \
0          354400      1345.0     2053691  ...        NaN        NaN      NaN   
1          410690      1356.0     2384299  ...        NaN        NaN     41.0   
2          314480      1449.0     2115891  ...        NaN        NaN     31.0   
3          421250      1550.0     2689960  ...        NaN        1.0     42.0   
4          420200      1550.0     3233812  ...     NÃO HÁ        NaN      NaN   
...           ...         ...         ...  ...        ...        ...      ...   
33784      350760      1342.0     2688433  ...        NaN        NaN      NaN   
33785      353760      1349.0     7135173  ...        NaN        3.0     35.0   
33786      170210         NaN     3654826  ...        NaN        NaN      NaN   
33787      352670      1345.0     2082462  ...        NaN        NaN      NaN   
33788      352880      1338.0     2041502  ...        NaN        NaN      NaN   

      COPAISINF  COMUNINF  AMBIENTE  DOENCA_TRA  EVOLUCAO  DT_OBITO  \
0             0       NaN       NaN         NaN       NaN       NaN   
1             1       NaN       NaN         NaN       NaN       NaN   
2             1  314710.0       3.0         2.0       NaN       NaN   
3             1  421250.0       1.0         2.0       1.0       NaN   
4             0       NaN       NaN         NaN       NaN       NaN   
...         ...       ...       ...         ...       ...       ...   
33784         0       NaN       NaN         NaN       9.0       NaN   
33785         1       NaN       1.0         2.0       1.0       NaN   
33786         0       NaN       NaN         NaN       NaN       NaN   
33787         0       NaN       NaN         NaN       1.0       NaN   
33788         0       NaN       NaN         NaN       1.0       NaN   

       DT_ENCERRA  
0      2007-02-07  
1      2007-06-22  
2             NaN  
3      2007-02-16  
4      2007-02-26  
...           ...  
33784  2021-03-04  
33785         NaN  
33786         NaN  
33787  2021-01-27  
33788  2021-02-22  

[33789 rows x 88 columns]

In [ ]:
df['SG_UF_NOT'] = df['SG_UF_NOT'].replace({11:'RO', 12: 'AC', 13: 'AM',
                                           14: 'RR', 15: 'PA', 16: 'AP', 17: 'TO', 21: 'MA', 22: 'PI',
                                           23: 'CE', 24: 'RN', 25: 'PB', 26: 'PE', 27: 'AL', 28: 'SE',
                                           29: 'BA', 31: 'MG', 32: 'ES', 33: 'RJ', 35: 'SP', 41: 'PR',
                                           42: 'SC', 43: 'RS', 50: 'MS', 51: 'MT', 52: 'GO', 53: 'DF'})
df

Unnamed: 0  TP_NOT ID_AGRAVO  DT_NOTIFIC  SEM_NOT  NU_ANO SG_UF_NOT  \
0               1       2      A779  2007-01-03   200701    2007        SP   
1               2       2      A779  2007-01-29   200705    2007        PR   
2               3       2      A779  2007-01-10   200702    2007        MG   
3               4       2      A779  2007-01-18   200703    2007        SC   
4               5       2      A779  2007-01-15   200703    2007        SC   
...           ...     ...       ...         ...      ...     ...       ...   
33784        1965       2      A779  2020-12-30   202053    2020        SP   
33785        1966       2      A779  2020-12-31   202053    2020        SP   
33786        1967       2      A779  2020-12-31   202053    2020        TO   
33787        1968       2      A779  2020-12-31   202053    2020        SP   
33788        1969       2      A779  2020-12-31   202053    2020        SP   

       ID_MUNICIP  ID_REGIONA  ID_UNIDADE  ... DIAG_DESCA  TPAUTOCTO  COUFINF  \
0          354400      1345.0     2053691  ...        NaN        NaN      NaN   
1          410690      1356.0     2384299  ...        NaN        NaN     41.0   
2          314480      1449.0     2115891  ...        NaN        NaN     31.0   
3          421250      1550.0     2689960  ...        NaN        1.0     42.0   
4          420200      1550.0     3233812  ...     NÃO HÁ        NaN      NaN   
...           ...         ...         ...  ...        ...        ...      ...   
33784      350760      1342.0     2688433  ...        NaN        NaN      NaN   
33785      353760      1349.0     7135173  ...        NaN        3.0     35.0   
33786      170210         NaN     3654826  ...        NaN        NaN      NaN   
33787      352670      1345.0     2082462  ...        NaN        NaN      NaN   
33788      352880      1338.0     2041502  ...        NaN        NaN      NaN   

      COPAISINF  COMUNINF  AMBIENTE  DOENCA_TRA  EVOLUCAO  DT_OBITO  \
0             0       NaN       NaN         NaN       NaN       NaN   
1             1       NaN       NaN         NaN       NaN       NaN   
2             1  314710.0       3.0         2.0       NaN       NaN   
3             1  421250.0       1.0         2.0       1.0       NaN   
4             0       NaN       NaN         NaN       NaN       NaN   
...         ...       ...       ...         ...       ...       ...   
33784         0       NaN       NaN         NaN       9.0       NaN   
33785         1       NaN       1.0         2.0       1.0       NaN   
33786         0       NaN       NaN         NaN       NaN       NaN   
33787         0       NaN       NaN         NaN       1.0       NaN   
33788         0       NaN       NaN         NaN       1.0       NaN   

       DT_ENCERRA  
0      2007-02-07  
1      2007-06-22  
2             NaN  
3      2007-02-16  
4      2007-02-26  
...           ...  
33784  2021-03-04  
33785         NaN  
33786         NaN  
33787  2021-01-27  
33788  2021-02-22  

[33789 rows x 88 columns]

In [ ]:
list(df.columns)


['Unnamed: 0',
 'TP_NOT',
 'ID_AGRAVO',
 'DT_NOTIFIC',
 'SEM_NOT',
 'NU_ANO',
 'SG_UF_NOT',
 'ID_MUNICIP',
 'ID_REGIONA',
 'ID_UNIDADE',
 'DT_SIN_PRI',
 'SEM_PRI',
 'NU_IDADE_N',
 'CS_SEXO',
 'CS_GESTANT',
 'CS_RACA',
 'CS_ESCOL_N',
 'SG_UF',
 'ID_MN_RESI',
 'ID_RG_RESI',
 'ID_PAIS',
 'DT_INVEST',
 'ID_OCUPA_N',
 'FEBRE',
 'CEFALEIA',
 'ABDOMINAL',
 'MIALGIA',
 'NAUSEA',
 'EXANTEMA',
 'DIARREIA',
 'ICTERICIA',
 'HIPEREMIA',
 'HEPATOME',
 'PETEQUIAS',
 'HEMORRAG',
 'LINFADENO',
 'CONVULSAO',
 'NECROSE',
 'PROSTACAO',
 'CHOQUE',
 'COMA',
 'HEMORRAGI',
 'RESPIRATO',
 'OLIGURIA',
 'OUTROS',
 'OUTRO_ESP',
 'CARRAPATO',
 'CAPIVARA',
 'CAO_GATO',
 'BOVINO',
 'EQUINOS',
 'OUTROANI',
 'ANIM_ESP',
 'FOI_MATA',
 'HOSPITAL',
 'DTINTERNA',
 'DTALTA',
 'COUFHOSP',
 'COMUNHOSP',
 'DIAGNO_LAB',
 'DTS1',
 'DTS2',
 'IGM_S1',
 'TIT_IGM_S1',
 'IGG_S1',
 'TIT_IGG_S1',
 'IGM_S2',
 'TIT_IGM_S2',
 'IGG_S2',
 'TIT_IGG_S2',
 'DT_COLETA',
 'DT_DIGITA',
 'ISOLAMENTO',
 'AGENTE',
 'HISTOPATO',
 'IMUNOHIST',
 'CLAS

In [ ]:
df['EVOLUCAO'].unique()

array([nan,  1.,  9.,  2.,  3.])

In [ ]:
df = df.drop_duplicates() #retirando as linhas que se repetem, duplicatas, 100% iguais.
df

Unnamed: 0  TP_NOT ID_AGRAVO  DT_NOTIFIC  SEM_NOT  NU_ANO SG_UF_NOT  \
0               1       2      A779  2007-01-03   200701    2007        SP   
1               2       2      A779  2007-01-29   200705    2007        PR   
2               3       2      A779  2007-01-10   200702    2007        MG   
3               4       2      A779  2007-01-18   200703    2007        SC   
4               5       2      A779  2007-01-15   200703    2007        SC   
...           ...     ...       ...         ...      ...     ...       ...   
33784        1965       2      A779  2020-12-30   202053    2020        SP   
33785        1966       2      A779  2020-12-31   202053    2020        SP   
33786        1967       2      A779  2020-12-31   202053    2020        TO   
33787        1968       2      A779  2020-12-31   202053    2020        SP   
33788        1969       2      A779  2020-12-31   202053    2020        SP   

       ID_MUNICIP  ID_REGIONA  ID_UNIDADE  ... DIAG_DESCA  TPAUTOCTO  COUFINF  \
0          354400      1345.0     2053691  ...        NaN        NaN      NaN   
1          410690      1356.0     2384299  ...        NaN        NaN     41.0   
2          314480      1449.0     2115891  ...        NaN        NaN     31.0   
3          421250      1550.0     2689960  ...        NaN        1.0     42.0   
4          420200      1550.0     3233812  ...     NÃO HÁ        NaN      NaN   
...           ...         ...         ...  ...        ...        ...      ...   
33784      350760      1342.0     2688433  ...        NaN        NaN      NaN   
33785      353760      1349.0     7135173  ...        NaN        3.0     35.0   
33786      170210         NaN     3654826  ...        NaN        NaN      NaN   
33787      352670      1345.0     2082462  ...        NaN        NaN      NaN   
33788      352880      1338.0     2041502  ...        NaN        NaN      NaN   

      COPAISINF  COMUNINF  AMBIENTE  DOENCA_TRA  EVOLUCAO  DT_OBITO  \
0             0       NaN       NaN         NaN       NaN       NaN   
1             1       NaN       NaN         NaN       NaN       NaN   
2             1  314710.0       3.0         2.0       NaN       NaN   
3             1  421250.0       1.0         2.0       1.0       NaN   
4             0       NaN       NaN         NaN       NaN       NaN   
...         ...       ...       ...         ...       ...       ...   
33784         0       NaN       NaN         NaN       9.0       NaN   
33785         1       NaN       1.0         2.0       1.0       NaN   
33786         0       NaN       NaN         NaN       NaN       NaN   
33787         0       NaN       NaN         NaN       1.0       NaN   
33788         0       NaN       NaN         NaN       1.0       NaN   

       DT_ENCERRA  
0      2007-02-07  
1      2007-06-22  
2             NaN  
3      2007-02-16  
4      2007-02-26  
...           ...  
33784  2021-03-04  
33785         NaN  
33786         NaN  
33787  2021-01-27  
33788  2021-02-22  

[33789 rows x 88 columns]

In [ ]:
len(list(df.columns))

88

# Tratamento da coluna de número de casos

In [ ]:
# 1. Confirmado
# 2. Descartado
df1 = df
df['CLASSI_FIN'].unique()

array([ 2., nan,  1.,  8.])

In [ ]:
df1.drop(df1.index[df1['CLASSI_FIN'] == 8.0], inplace=True)

In [ ]:
df1['CLASSI_FIN'].unique()

array([ 2., nan,  1.])

In [ ]:
df1 = df1.dropna(subset=['CLASSI_FIN'])

In [ ]:
df1['CLASSI_FIN'].unique()

array([2., 1.])

In [ ]:
df1.shape[0]

2295

In [ ]:
df1.drop(df1.index[df1['CLASSI_FIN'] == 2.0],  inplace=True) #só me interessa quem testar positivo, ou seja, o valor 1, para quando for somar obter só a quantidade dos positivos.

<ipython-input-47-c39d882b6db2>:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df1.drop(df1.index[df1['CLASSI_FIN'] == 2.0],  inplace=True) #só me interessa quem testar positivo, ou seja, o valor 1, para quando for somar obter só a quantidade dos positivos.


In [ ]:
df1['CLASSI_FIN'].unique()

array([1.])

In [ ]:
df1.shape

(2295, 88)

In [ ]:
df1['EVOLUCAO'].value_counts()

1.0    1400
2.0     759
9.0      45
3.0      26
Name: EVOLUCAO, dtype: int64

# tratamento da coluna de óbitos:

In [ ]:
# 1. Cura
# 2. Óbito por Febre Maculosa
# 3. Óbito por outra causa
# 9. ignorado

df2 = df1
df2['EVOLUCAO'].unique()

array([ 1.,  2.,  3., nan,  9.])

In [ ]:
df2['EVOLUCAO'].value_counts()

1.0    1400
2.0     759
9.0      45
3.0      26
Name: EVOLUCAO, dtype: int64

In [ ]:
# Excluindo os NANS
df2 = df.dropna(subset=['EVOLUCAO'])
df2['EVOLUCAO'].unique()

array([1., 2., 3., 9.])

In [ ]:
#Excluindo o número 1 na coluna:

df2.drop(df2.index[df2['EVOLUCAO'] == 1.0],  inplace=True)
df2['EVOLUCAO'].unique()

<ipython-input-21-f330dd3beded>:3: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df2.drop(df2.index[df2['EVOLUCAO'] == 1.0],  inplace=True)


array([2., 3., 9.])

In [ ]:
#Excluindo o número 3 na coluna:

df2.drop(df2.index[df2['EVOLUCAO'] == 3.0], inplace=True)
df2['EVOLUCAO'].unique()

<ipython-input-22-cde04c07eb99>:3: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df2.drop(df2.index[df2['EVOLUCAO'] == 3.0], inplace=True)


array([2., 9.])

In [ ]:
#Excluindo o número 9 na coluna:

df2.drop(df2.index[df2['EVOLUCAO'] == 9.0], inplace = True)
df2['EVOLUCAO'].unique()

<ipython-input-23-64a454a6b94c>:3: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df2.drop(df2.index[df2['EVOLUCAO'] == 9.0], inplace = True)


array([2.])

In [ ]:
df2['EVOLUCAO'].value_counts()

2.0    770
Name: EVOLUCAO, dtype: int64

In [ ]:
df2.shape

(770, 88)

In [ ]:
df2['SG_UF_NOT'].unique()

array(['MG', 'RJ', 'SP', 'PR', 'ES', 'PE', 'AM'], dtype=object)

# ***Novo dataframe (óbitos)***

In [ ]:
result = df2.groupby(['NU_ANO','SG_UF_NOT'])['EVOLUCAO'].sum().reset_index()
anos = df['NU_ANO'].unique()
estados = df['SG_UF_NOT'].unique()
for ano in anos:
  for estado in estados:
    if not ((result['NU_ANO'] == ano) & (result['SG_UF_NOT'] == estado)).any():
      result = result.append({'NU_ANO': ano, 'SG_UF_NOT': estado, 'EVOLUCAO': 0}, ignore_index=True)





result = result.rename(columns={'NU_ANO': 'Ano'})
result = result.rename(columns={'SG_UF_NOT': 'Sigla'})
result = result.rename(columns={'EVOLUCAO': 'Óbitos'})
result


siglas_estados = {
    'RO': 'Rondônia',
    'AC': 'Acre',
    'AM': 'Amazonas',
    'RR': 'Roraima',
    'PA': 'Pará',
    'AP': 'Amapá',
    'TO': 'Tocantins',
    'MA': 'Maranhão',
    'PI': 'Piauí',
    'CE': 'Ceará',
    'RN': 'Rio Grande do Norte',
    'PB': 'Paraíba',
    'PE': 'Pernambuco',
    'AL': 'Alagoas',
    'SE': 'Sergipe',
    'BA': 'Bahia',
    'MG': 'Minas Gerais',
    'ES': 'Espírito Santo',
    'RJ': 'Rio de Janeiro',
    'SP': 'São Paulo',
    'PR': 'Paraná',
    'SC': 'Santa Catarina',
    'RS': 'Rio Grande do Sul',
    'MS': 'Mato Grosso do Sul',
    'MT': 'Mato Grosso',
    'GO': 'Goiás',
    'DF': 'Distrito Federal'
}

result['Estado'] = result['Sigla'].map(siglas_estados)
result['Óbitos'] = result['Óbitos'].astype(int)
result = result[['Estado', 'Sigla', 'Ano', 'Óbitos']]
result


<ipython-input-27-1d01dcb82f79>:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  result = result.append({'NU_ANO': ano, 'SG_UF_NOT': estado, 'EVOLUCAO': 0}, ignore_index=True)
<ipython-input-27-1d01dcb82f79>:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  result = result.append({'NU_ANO': ano, 'SG_UF_NOT': estado, 'EVOLUCAO': 0}, ignore_index=True)
<ipython-input-27-1d01dcb82f79>:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  result = result.append({'NU_ANO': ano, 'SG_UF_NOT': estado, 'EVOLUCAO': 0}, ignore_index=True)
<ipython-input-27-1d01dcb82f79>:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  result = result.append({'NU_ANO': a

Estado Sigla   Ano  Óbitos
0      Minas Gerais    MG  2007      14
1    Rio de Janeiro    RJ  2007      10
2         São Paulo    SP  2007      20
3      Minas Gerais    MG  2008      16
4    Rio de Janeiro    RJ  2008       8
..              ...   ...   ...     ...
373            Acre    AC  2020       0
374         Roraima    RR  2020       0
375           Piauí    PI  2020       0
376         Alagoas    AL  2020       0
377         Sergipe    SE  2020       0

[378 rows x 4 columns]

# ***Novo dataframe (numero de casos)***

In [ ]:
result1 = df1.groupby(['NU_ANO','SG_UF_NOT'])['CLASSI_FIN'].sum().reset_index()

anos = df['NU_ANO'].unique()
estados = df['SG_UF_NOT'].unique()
for ano in anos:
  for estado in estados:
    if not ((result1['NU_ANO'] == ano) & (result1['SG_UF_NOT'] == estado)).any():
      result1 = result1.append({'NU_ANO': ano, 'SG_UF_NOT': estado, 'CLASSI_FIN': 0}, ignore_index=True)

result1 = result1.rename(columns={'NU_ANO': 'Ano'})
result1 = result1.rename(columns={'SG_UF_NOT': 'Sigla'})
result1 = result1.rename(columns={'CLASSI_FIN': 'N_CASOS'})
result1


siglas_estados = {
    'RO': 'Rondônia',
    'AC': 'Acre',
    'AM': 'Amazonas',
    'RR': 'Roraima',
    'PA': 'Pará',
    'AP': 'Amapá',
    'TO': 'Tocantins',
    'MA': 'Maranhão',
    'PI': 'Piauí',
    'CE': 'Ceará',
    'RN': 'Rio Grande do Norte',
    'PB': 'Paraíba',
    'PE': 'Pernambuco',
    'AL': 'Alagoas',
    'SE': 'Sergipe',
    'BA': 'Bahia',
    'MG': 'Minas Gerais',
    'ES': 'Espírito Santo',
    'RJ': 'Rio de Janeiro',
    'SP': 'São Paulo',
    'PR': 'Paraná',
    'SC': 'Santa Catarina',
    'RS': 'Rio Grande do Sul',
    'MS': 'Mato Grosso do Sul',
    'MT': 'Mato Grosso',
    'GO': 'Goiás',
    'DF': 'Distrito Federal'
}

result1['Estado'] = result1['Sigla'].map(siglas_estados)
result1['N_CASOS'] = result1['N_CASOS'].astype(int)
result1 = result1[['Estado', 'Sigla', 'Ano', 'N_CASOS']]
result1

<ipython-input-28-80771e07268c>:8: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  result1 = result1.append({'NU_ANO': ano, 'SG_UF_NOT': estado, 'CLASSI_FIN': 0}, ignore_index=True)
<ipython-input-28-80771e07268c>:8: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  result1 = result1.append({'NU_ANO': ano, 'SG_UF_NOT': estado, 'CLASSI_FIN': 0}, ignore_index=True)
<ipython-input-28-80771e07268c>:8: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  result1 = result1.append({'NU_ANO': ano, 'SG_UF_NOT': estado, 'CLASSI_FIN': 0}, ignore_index=True)
<ipython-input-28-80771e07268c>:8: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  result1 = result1.appen

Estado Sigla   Ano  N_CASOS
0       Espírito Santo    ES  2007        4
1         Minas Gerais    MG  2007       14
2               Paraná    PR  2007        2
3       Rio de Janeiro    RJ  2007       14
4    Rio Grande do Sul    RS  2007        2
..                 ...   ...   ...      ...
373               Acre    AC  2020        0
374            Roraima    RR  2020        0
375              Piauí    PI  2020        0
376            Alagoas    AL  2020        0
377            Sergipe    SE  2020        0

[378 rows x 4 columns]

In [ ]:
df_joined = pd.merge(result1[['Estado','Sigla', 'Ano', 'N_CASOS']], result[['Estado','Sigla', 'Ano', 'Óbitos']], on=['Estado','Ano', 'Sigla'])

df_joined.to_csv('arquivo.csv', index=False)
df_joined


Estado Sigla   Ano  N_CASOS  Óbitos
0       Espírito Santo    ES  2007        4       0
1         Minas Gerais    MG  2007       14      14
2               Paraná    PR  2007        2       0
3       Rio de Janeiro    RJ  2007       14      10
4    Rio Grande do Sul    RS  2007        2       0
..                 ...   ...   ...      ...     ...
373               Acre    AC  2020        0       0
374            Roraima    RR  2020        0       0
375              Piauí    PI  2020        0       0
376            Alagoas    AL  2020        0       0
377            Sergipe    SE  2020        0       0

[378 rows x 5 columns]

In [ ]:
df_joined[df_joined["Estado"] == "Minas Gerais"]

Estado Sigla   Ano  N_CASOS  Óbitos
1    Minas Gerais    MG  2007       14      14
8    Minas Gerais    MG  2008       11      16
14   Minas Gerais    MG  2009       12       8
23   Minas Gerais    MG  2010       12       6
31   Minas Gerais    MG  2011       18      14
40   Minas Gerais    MG  2012       10       8
48   Minas Gerais    MG  2013       16      12
56   Minas Gerais    MG  2014       13      14
65   Minas Gerais    MG  2015       20      10
78   Minas Gerais    MG  2016       23      12
88   Minas Gerais    MG  2017       41      38
102  Minas Gerais    MG  2018       76      52
116  Minas Gerais    MG  2019       89      48
126  Minas Gerais    MG  2020       27      16

In [ ]:
df_joined['N_CASOS'].sum()

2295