<a href="https://colab.research.google.com/github/washingtonjr8/PIBIC/blob/main/Numero_de_casos_e_%C3%B3bitos_(LV).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [ ]:
path = '/content/drive/MyDrive/Colab Notebooks/PIBIC/'
ano_inicio = 7
ano_fim = 23
input_files = ['LEIVBR'+ str(ano)+'.csv' for ano in range(ano_inicio, ano_fim)]

df_list = []

for file in input_files:
    df_list.append(pd.read_csv(path+file, encoding='latin1', index_col=False, engine='python',on_bad_lines='skip', delimiter = ';'))

df = pd.concat(df_list, axis=0, ignore_index=True)
df




Unnamed: 0  TP_NOT ID_AGRAVO  DT_NOTIFIC  SEM_NOT  NU_ANO  SG_UF_NOT  \
0                1       2      B550  2007-01-02   200701    2007         31   
1                2       2      B550  2007-01-02   200701    2007         31   
2                3       2      B550  2007-01-03   200701    2007         22   
3                4       2      B550  2007-01-03   200701    2007         17   
4                5       2      B550  2007-01-04   200701    2007         35   
...            ...     ...       ...         ...      ...     ...        ...   
143664        7972       2      B550  2022-12-31   202252    2022         21   
143665        7973       2      B550  2022-12-31   202252    2022         50   
143666        7974       2      B550  2022-12-31   202252    2022         50   
143667        7975       2      B550  2022-12-31   202252    2022         31   
143668        7976       2      B550  2022-12-31   202252    2022         35   

        ID_MUNICIP  ID_REGIONA  DT_SIN_PRI  ...  CO_PAIS_2 DS_TRANS_2  \
0           310620      1449.0  2006-12-16  ...        NaN        NaN   
1           310620      1449.0  2006-12-09  ...        NaN        NaN   
2           221100      1883.0  2007-01-03  ...        NaN        NaN   
3           171820         NaN  2006-10-09  ...        NaN        NaN   
4           351300      1335.0  2006-02-23  ...        NaN        NaN   
...            ...         ...         ...  ...        ...        ...   
143664      210530      1440.0  2022-12-30  ...        NaN        NaN   
143665      500270      1975.0  2022-09-30  ...        NaN        NaN   
143666      500830      6255.0  2022-11-30  ...        NaN        NaN   
143667      312090      1467.0  2022-12-30  ...        NaN        NaN   
143668      355500      1344.0  2022-10-31  ...        NaN        NaN   

        DT_DESLC3 DS_MUN_3  CO_UF_3  CO_PAIS_3  DS_TRANS_3  ID_UNIDADE  \
0             NaN      NaN      NaN        NaN         NaN         NaN   
1             NaN      NaN      NaN        NaN         NaN         NaN   
2             NaN      NaN      NaN        NaN         NaN         NaN   
3             NaN      NaN      NaN        NaN         NaN         NaN   
4             NaN      NaN      NaN        NaN         NaN         NaN   
...           ...      ...      ...        ...         ...         ...   
143664        NaN      NaN      NaN        NaN         NaN   2456672.0   
143665        NaN      NaN      NaN        NaN         NaN      9733.0   
143666        NaN      NaN      NaN        NaN         NaN   2757060.0   
143667        NaN      NaN      NaN        NaN         NaN   2204762.0   
143668        NaN      NaN      NaN        NaN         NaN   2080664.0   

        ANO_NASC   DT_DIGITA  
0            NaN         NaN  
1            NaN         NaN  
2            NaN         NaN  
3            NaN         NaN  
4            NaN         NaN  
...          ...         ...  
143664    2022.0  2023-01-24  
143665    1981.0  2023-01-05  
143666    1990.0  2023-02-06  
143667    2002.0  2023-01-04  
143668    1952.0  2023-01-10  

[143669 rows x 79 columns]

In [ ]:
df['SG_UF_NOT'] = df['SG_UF_NOT'].replace({11:'RO', 12: 'AC', 13: 'AM',
                                           14: 'RR', 15: 'PA', 16: 'AP', 17: 'TO', 21: 'MA', 22: 'PI',
                                           23: 'CE', 24: 'RN', 25: 'PB', 26: 'PE', 27: 'AL', 28: 'SE',
                                           29: 'BA', 31: 'MG', 32: 'ES', 33: 'RJ', 35: 'SP', 41: 'PR',
                                           42: 'SC', 43: 'RS', 50: 'MS', 51: 'MT', 52: 'GO', 53: 'DF'})
df

Unnamed: 0  TP_NOT ID_AGRAVO  DT_NOTIFIC  SEM_NOT  NU_ANO SG_UF_NOT  \
0                1       2      B550  2007-01-02   200701    2007        MG   
1                2       2      B550  2007-01-02   200701    2007        MG   
2                3       2      B550  2007-01-03   200701    2007        PI   
3                4       2      B550  2007-01-03   200701    2007        TO   
4                5       2      B550  2007-01-04   200701    2007        SP   
...            ...     ...       ...         ...      ...     ...       ...   
143664        7972       2      B550  2022-12-31   202252    2022        MA   
143665        7973       2      B550  2022-12-31   202252    2022        MS   
143666        7974       2      B550  2022-12-31   202252    2022        MS   
143667        7975       2      B550  2022-12-31   202252    2022        MG   
143668        7976       2      B550  2022-12-31   202252    2022        SP   

        ID_MUNICIP  ID_REGIONA  DT_SIN_PRI  ...  CO_PAIS_2 DS_TRANS_2  \
0           310620      1449.0  2006-12-16  ...        NaN        NaN   
1           310620      1449.0  2006-12-09  ...        NaN        NaN   
2           221100      1883.0  2007-01-03  ...        NaN        NaN   
3           171820         NaN  2006-10-09  ...        NaN        NaN   
4           351300      1335.0  2006-02-23  ...        NaN        NaN   
...            ...         ...         ...  ...        ...        ...   
143664      210530      1440.0  2022-12-30  ...        NaN        NaN   
143665      500270      1975.0  2022-09-30  ...        NaN        NaN   
143666      500830      6255.0  2022-11-30  ...        NaN        NaN   
143667      312090      1467.0  2022-12-30  ...        NaN        NaN   
143668      355500      1344.0  2022-10-31  ...        NaN        NaN   

        DT_DESLC3 DS_MUN_3  CO_UF_3  CO_PAIS_3  DS_TRANS_3  ID_UNIDADE  \
0             NaN      NaN      NaN        NaN         NaN         NaN   
1             NaN      NaN      NaN        NaN         NaN         NaN   
2             NaN      NaN      NaN        NaN         NaN         NaN   
3             NaN      NaN      NaN        NaN         NaN         NaN   
4             NaN      NaN      NaN        NaN         NaN         NaN   
...           ...      ...      ...        ...         ...         ...   
143664        NaN      NaN      NaN        NaN         NaN   2456672.0   
143665        NaN      NaN      NaN        NaN         NaN      9733.0   
143666        NaN      NaN      NaN        NaN         NaN   2757060.0   
143667        NaN      NaN      NaN        NaN         NaN   2204762.0   
143668        NaN      NaN      NaN        NaN         NaN   2080664.0   

        ANO_NASC   DT_DIGITA  
0            NaN         NaN  
1            NaN         NaN  
2            NaN         NaN  
3            NaN         NaN  
4            NaN         NaN  
...          ...         ...  
143664    2022.0  2023-01-24  
143665    1981.0  2023-01-05  
143666    1990.0  2023-02-06  
143667    2002.0  2023-01-04  
143668    1952.0  2023-01-10  

[143669 rows x 79 columns]

In [ ]:
list(df.columns)


['Unnamed: 0',
 'TP_NOT',
 'ID_AGRAVO',
 'DT_NOTIFIC',
 'SEM_NOT',
 'NU_ANO',
 'SG_UF_NOT',
 'ID_MUNICIP',
 'ID_REGIONA',
 'DT_SIN_PRI',
 'SEM_PRI',
 'DT_NASC',
 'NU_IDADE_N',
 'CS_SEXO',
 'CS_GESTANT',
 'CS_RACA',
 'CS_ESCOL_N',
 'SG_UF',
 'ID_MN_RESI',
 'ID_RG_RESI',
 'ID_PAIS',
 'NDUPLIC_N',
 'CS_FLXRET',
 'FLXRECEBI',
 'MIGRADO_W',
 'DT_INVEST',
 'ID_OCUPA_N',
 'FEBRE',
 'FRAQUEZA',
 'EDEMA',
 'EMAGRA',
 'TOSSE',
 'PALIDEZ',
 'BACO',
 'INFECCIOSO',
 'FEN_HEMORR',
 'FIGADO',
 'ICTERICIA',
 'OUTROS',
 'OUTROS_ESP',
 'HIV',
 'DIAG_PAR_N',
 'IFI',
 'OUTRO',
 'ENTRADA',
 'TRATAMENTO',
 'DROGA',
 'PESO',
 'DOSE',
 'AMPOLAS',
 'FALENCIA',
 'CLASSI_FIN',
 'CRITERIO',
 'TPAUTOCTO',
 'COUFINF',
 'COPAISINF',
 'COMUNINF',
 'DOENCA_TRA',
 'EVOLUCAO',
 'DT_OBITO',
 'DT_ENCERRA',
 'DT_DESLC1',
 'DS_MUN_1',
 'CO_UF_1',
 'CO_PAIS_1',
 'DS_TRANS_1',
 'DT_DESLC2',
 'DS_MUN_2',
 'CO_UF_2',
 'CO_PAIS_2',
 'DS_TRANS_2',
 'DT_DESLC3',
 'DS_MUN_3',
 'CO_UF_3',
 'CO_PAIS_3',
 'DS_TRANS_3',
 'ID_UNIDADE',


In [ ]:
df = df.drop_duplicates() #retirando as linhas que se repetem, duplicatas, 100% iguais.
df

Unnamed: 0  TP_NOT ID_AGRAVO  DT_NOTIFIC  SEM_NOT  NU_ANO SG_UF_NOT  \
0                1       2      B550  2007-01-02   200701    2007        MG   
1                2       2      B550  2007-01-02   200701    2007        MG   
2                3       2      B550  2007-01-03   200701    2007        PI   
3                4       2      B550  2007-01-03   200701    2007        TO   
4                5       2      B550  2007-01-04   200701    2007        SP   
...            ...     ...       ...         ...      ...     ...       ...   
143664        7972       2      B550  2022-12-31   202252    2022        MA   
143665        7973       2      B550  2022-12-31   202252    2022        MS   
143666        7974       2      B550  2022-12-31   202252    2022        MS   
143667        7975       2      B550  2022-12-31   202252    2022        MG   
143668        7976       2      B550  2022-12-31   202252    2022        SP   

        ID_MUNICIP  ID_REGIONA  DT_SIN_PRI  ...  CO_PAIS_2 DS_TRANS_2  \
0           310620      1449.0  2006-12-16  ...        NaN        NaN   
1           310620      1449.0  2006-12-09  ...        NaN        NaN   
2           221100      1883.0  2007-01-03  ...        NaN        NaN   
3           171820         NaN  2006-10-09  ...        NaN        NaN   
4           351300      1335.0  2006-02-23  ...        NaN        NaN   
...            ...         ...         ...  ...        ...        ...   
143664      210530      1440.0  2022-12-30  ...        NaN        NaN   
143665      500270      1975.0  2022-09-30  ...        NaN        NaN   
143666      500830      6255.0  2022-11-30  ...        NaN        NaN   
143667      312090      1467.0  2022-12-30  ...        NaN        NaN   
143668      355500      1344.0  2022-10-31  ...        NaN        NaN   

        DT_DESLC3 DS_MUN_3  CO_UF_3  CO_PAIS_3  DS_TRANS_3  ID_UNIDADE  \
0             NaN      NaN      NaN        NaN         NaN         NaN   
1             NaN      NaN      NaN        NaN         NaN         NaN   
2             NaN      NaN      NaN        NaN         NaN         NaN   
3             NaN      NaN      NaN        NaN         NaN         NaN   
4             NaN      NaN      NaN        NaN         NaN         NaN   
...           ...      ...      ...        ...         ...         ...   
143664        NaN      NaN      NaN        NaN         NaN   2456672.0   
143665        NaN      NaN      NaN        NaN         NaN      9733.0   
143666        NaN      NaN      NaN        NaN         NaN   2757060.0   
143667        NaN      NaN      NaN        NaN         NaN   2204762.0   
143668        NaN      NaN      NaN        NaN         NaN   2080664.0   

        ANO_NASC   DT_DIGITA  
0            NaN         NaN  
1            NaN         NaN  
2            NaN         NaN  
3            NaN         NaN  
4            NaN         NaN  
...          ...         ...  
143664    2022.0  2023-01-24  
143665    1981.0  2023-01-05  
143666    1990.0  2023-02-06  
143667    2002.0  2023-01-04  
143668    1952.0  2023-01-10  

[143669 rows x 79 columns]

In [ ]:
len(list(df.columns))

79

# Tratamento da coluna de número de casos

In [ ]:
# 1. Confirmado
# 2. Descartado
df1 = df
df['CLASSI_FIN'].unique()

array([ 2.,  1., nan,  8.,  0.])

In [ ]:
df1.drop(df1.index[df1['CLASSI_FIN'] == 0.0], inplace=True)

In [ ]:
df1['CLASSI_FIN'].unique()

array([ 2.,  1., nan,  8.])

In [ ]:
df1.drop(df1.index[df1['CLASSI_FIN'] == 8.0], inplace=True)

In [ ]:
df1['CLASSI_FIN'].unique()

array([ 2.,  1., nan])

In [ ]:
df1 = df1.dropna(subset=['CLASSI_FIN'])

In [ ]:
df1['CLASSI_FIN'].unique()

array([2., 1.])

In [ ]:
df1.shape[0]

132733

In [ ]:
df1.drop(df1.index[df1['CLASSI_FIN'] == 2.0],  inplace=True) #só me interessa quem testar positivo, ou seja, o valor 1, para quando for somar obter só a quantidade dos positivos.

<ipython-input-20-c39d882b6db2>:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df1.drop(df1.index[df1['CLASSI_FIN'] == 2.0],  inplace=True) #só me interessa quem testar positivo, ou seja, o valor 1, para quando for somar obter só a quantidade dos positivos.


In [ ]:
df1['CLASSI_FIN'].unique()
df1.shape

(54115, 79)

In [ ]:
df1['SG_UF_NOT'].unique()

array(['PI', 'BA', 'MS', 'SE', 'PE', 'MG', 'CE', 'TO', 'SP', 'DF', 'PA',
       'MA', 'RN', 'AL', 'MT', 'PB', 'SC', 'GO', 'RR', 'PR', 'RO', 'AP',
       'RJ', 'AM', 'ES', 'RS'], dtype=object)

In [ ]:
df1['EVOLUCAO'].value_counts()

1.0    37784
3.0     3769
5.0     3410
4.0     1249
2.0      405
Name: EVOLUCAO, dtype: int64

# tratamento da coluna de óbitos:

In [ ]:
# 1. Cura
# 2. Abandono
# 3. Óbito por LV
# 4. Óbito por outras causas
# 5. Transferência
df2 = df1


In [ ]:
df2['EVOLUCAO'].unique()

array([nan,  1.,  3.,  2.,  5.,  4.])

In [ ]:
df2['EVOLUCAO'].value_counts()

1.0    37784
3.0     3769
5.0     3410
4.0     1249
2.0      405
Name: EVOLUCAO, dtype: int64

In [ ]:
# Excluindo os NANS
df2 = df.dropna(subset=['EVOLUCAO'])
df2['EVOLUCAO'].unique()

array([1., 3., 2., 5., 4., 0.])

In [ ]:
#Excluindo o número 1 na coluna:

df2.drop(df2.index[df2['EVOLUCAO'] == 1.0],  inplace=True)
df2['EVOLUCAO'].unique()

<ipython-input-28-f330dd3beded>:3: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df2.drop(df2.index[df2['EVOLUCAO'] == 1.0],  inplace=True)


array([3., 2., 5., 4., 0.])

In [ ]:
#Excluindo o número 2 na coluna:

df2.drop(df2.index[df2['EVOLUCAO'] == 2.0], inplace=True)
df2['EVOLUCAO'].unique()

<ipython-input-29-2d6d76d112d8>:3: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df2.drop(df2.index[df2['EVOLUCAO'] == 2.0], inplace=True)


array([3., 5., 4., 0.])

In [ ]:
#Excluindo o número 4 na coluna:

df2.drop(df2.index[df2['EVOLUCAO'] == 4.0], inplace = True)
df2['EVOLUCAO'].unique()

<ipython-input-30-0cca605b2206>:3: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df2.drop(df2.index[df2['EVOLUCAO'] == 4.0], inplace = True)


array([3., 5., 0.])

In [ ]:
#Excluindo o número 5 na coluna:

df2.drop(df2.index[df2['EVOLUCAO'] == 5.0], inplace = True)
df2.drop(df2.index[df2['EVOLUCAO'] == 0.0], inplace = True)
df2['EVOLUCAO'].unique()

<ipython-input-31-d21de156e3e2>:3: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df2.drop(df2.index[df2['EVOLUCAO'] == 5.0], inplace = True)
<ipython-input-31-d21de156e3e2>:4: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df2.drop(df2.index[df2['EVOLUCAO'] == 0.0], inplace = True)


array([3.])

In [ ]:
df2['EVOLUCAO'].value_counts()

3.0    3771
Name: EVOLUCAO, dtype: int64

In [ ]:
df2['EVOLUCAO'].value_counts()

3.0    3771
Name: EVOLUCAO, dtype: int64

In [ ]:
df2['SG_UF_NOT'].unique()

array(['BA', 'TO', 'SE', 'PA', 'MA', 'MS', 'PI', 'MG', 'PB', 'PE', 'DF',
       'SP', 'AL', 'MT', 'CE', 'GO', 'RN', 'RR', 'PR', 'AM', 'ES', 'RJ',
       'RO', 'RS'], dtype=object)

# ***Novo dataframe (óbitos)***

In [ ]:
result = df2.groupby(['NU_ANO','SG_UF_NOT'])['EVOLUCAO'].sum().reset_index()
anos = df['NU_ANO'].unique()
estados = df['SG_UF_NOT'].unique()
for ano in anos:
  for estado in estados:
    if not ((result['NU_ANO'] == ano) & (result['SG_UF_NOT'] == estado)).any():
      result = result.append({'NU_ANO': ano, 'SG_UF_NOT': estado, 'EVOLUCAO': 0}, ignore_index=True)





result = result.rename(columns={'NU_ANO': 'Ano'})
result = result.rename(columns={'SG_UF_NOT': 'Sigla'})
result = result.rename(columns={'EVOLUCAO': 'Óbitos'})
result


siglas_estados = {
    'RO': 'Rondônia',
    'AC': 'Acre',
    'AM': 'Amazonas',
    'RR': 'Roraima',
    'PA': 'Pará',
    'AP': 'Amapá',
    'TO': 'Tocantins',
    'MA': 'Maranhão',
    'PI': 'Piauí',
    'CE': 'Ceará',
    'RN': 'Rio Grande do Norte',
    'PB': 'Paraíba',
    'PE': 'Pernambuco',
    'AL': 'Alagoas',
    'SE': 'Sergipe',
    'BA': 'Bahia',
    'MG': 'Minas Gerais',
    'ES': 'Espírito Santo',
    'RJ': 'Rio de Janeiro',
    'SP': 'São Paulo',
    'PR': 'Paraná',
    'SC': 'Santa Catarina',
    'RS': 'Rio Grande do Sul',
    'MS': 'Mato Grosso do Sul',
    'MT': 'Mato Grosso',
    'GO': 'Goiás',
    'DF': 'Distrito Federal'
}

result['Estado'] = result['Sigla'].map(siglas_estados)
result['Óbitos'] = result['Óbitos'].astype(int)
result = result[['Estado', 'Sigla', 'Ano', 'Óbitos']]
result


<ipython-input-35-1d01dcb82f79>:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  result = result.append({'NU_ANO': ano, 'SG_UF_NOT': estado, 'EVOLUCAO': 0}, ignore_index=True)
<ipython-input-35-1d01dcb82f79>:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  result = result.append({'NU_ANO': ano, 'SG_UF_NOT': estado, 'EVOLUCAO': 0}, ignore_index=True)
<ipython-input-35-1d01dcb82f79>:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  result = result.append({'NU_ANO': ano, 'SG_UF_NOT': estado, 'EVOLUCAO': 0}, ignore_index=True)
<ipython-input-35-1d01dcb82f79>:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  result = result.append({'NU_ANO': a

Estado Sigla   Ano  Óbitos
0              Alagoas    AL  2007       9
1                Bahia    BA  2007      48
2                Ceará    CE  2007      66
3     Distrito Federal    DF  2007       6
4                Goiás    GO  2007       6
..                 ...   ...   ...     ...
427              Amapá    AP  2022       0
428     Espírito Santo    ES  2022       0
429           Amazonas    AM  2022       0
430  Rio Grande do Sul    RS  2022       0
431               Acre    AC  2022       0

[432 rows x 4 columns]

# ***Novo dataframe (numero de casos)***

In [ ]:
result1 = df1.groupby(['NU_ANO','SG_UF_NOT'])['CLASSI_FIN'].sum().reset_index()

anos = df['NU_ANO'].unique()
estados = df['SG_UF_NOT'].unique()
for ano in anos:
  for estado in estados:
    if not ((result1['NU_ANO'] == ano) & (result1['SG_UF_NOT'] == estado)).any():
      result1 = result1.append({'NU_ANO': ano, 'SG_UF_NOT': estado, 'CLASSI_FIN': 0}, ignore_index=True)

result1 = result1.rename(columns={'NU_ANO': 'Ano'})
result1 = result1.rename(columns={'SG_UF_NOT': 'Sigla'})
result1 = result1.rename(columns={'CLASSI_FIN': 'N_CASOS'})
result1


siglas_estados = {
    'RO': 'Rondônia',
    'AC': 'Acre',
    'AM': 'Amazonas',
    'RR': 'Roraima',
    'PA': 'Pará',
    'AP': 'Amapá',
    'TO': 'Tocantins',
    'MA': 'Maranhão',
    'PI': 'Piauí',
    'CE': 'Ceará',
    'RN': 'Rio Grande do Norte',
    'PB': 'Paraíba',
    'PE': 'Pernambuco',
    'AL': 'Alagoas',
    'SE': 'Sergipe',
    'BA': 'Bahia',
    'MG': 'Minas Gerais',
    'ES': 'Espírito Santo',
    'RJ': 'Rio de Janeiro',
    'SP': 'São Paulo',
    'PR': 'Paraná',
    'SC': 'Santa Catarina',
    'RS': 'Rio Grande do Sul',
    'MS': 'Mato Grosso do Sul',
    'MT': 'Mato Grosso',
    'GO': 'Goiás',
    'DF': 'Distrito Federal'
}

result1['Estado'] = result1['Sigla'].map(siglas_estados)
result1['N_CASOS'] = result1['N_CASOS'].astype(int)
result1 = result1[['Estado', 'Sigla', 'Ano', 'N_CASOS']]
result1

<ipython-input-33-80771e07268c>:8: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  result1 = result1.append({'NU_ANO': ano, 'SG_UF_NOT': estado, 'CLASSI_FIN': 0}, ignore_index=True)
<ipython-input-33-80771e07268c>:8: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  result1 = result1.append({'NU_ANO': ano, 'SG_UF_NOT': estado, 'CLASSI_FIN': 0}, ignore_index=True)
<ipython-input-33-80771e07268c>:8: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  result1 = result1.append({'NU_ANO': ano, 'SG_UF_NOT': estado, 'CLASSI_FIN': 0}, ignore_index=True)
<ipython-input-33-80771e07268c>:8: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  result1 = result1.appen

Estado Sigla   Ano  N_CASOS
0           Alagoas    AL  2007       32
1          Amazonas    AM  2007        1
2             Amapá    AP  2007        1
3             Bahia    BA  2007      233
4             Ceará    CE  2007      550
..              ...   ...   ...      ...
427            Acre    AC  2021        0
428        Rondônia    RO  2022        0
429  Espírito Santo    ES  2022        0
430        Amazonas    AM  2022        0
431            Acre    AC  2022        0

[432 rows x 4 columns]

In [ ]:
df_joined = pd.merge(result1[['Estado','Sigla', 'Ano', 'N_CASOS']], result[['Estado','Sigla', 'Ano', 'Óbitos']], on=['Estado','Ano', 'Sigla'])

df_joined.to_csv('arquivo.csv', index=False)
df_joined


Estado Sigla   Ano  N_CASOS  Óbitos
0           Alagoas    AL  2007       32       9
1          Amazonas    AM  2007        1       0
2             Amapá    AP  2007        1       0
3             Bahia    BA  2007      233      48
4             Ceará    CE  2007      550      66
..              ...   ...   ...      ...     ...
427            Acre    AC  2021        0       0
428        Rondônia    RO  2022        0       0
429  Espírito Santo    ES  2022        0       0
430        Amazonas    AM  2022        0       0
431            Acre    AC  2022        0       0

[432 rows x 5 columns]

In [ ]:
correlacao = df_joined['N_CASOS'].corr(df_joined['Óbitos'])
correlacao*100

90.6362860170902